install.packages("tidyverse")
install.packages("data.table")
list.files()
#CSVFILES
e=read.csv(file ="BGSREC.csv", sep= ",", header=T, stringsAsFactors = F )
e
e1=read.csv(file ="CRUISES.csv", sep= ",", header=T, stringsAsFactors = F )
e2=read.csv(file ="CTDCASTREC.csv", sep= ",", header=T, stringsAsFactors = F )
e3=read.csv(file ="CTDREC.csv", sep= ",", header=T, stringsAsFactors = F )
e4=read.csv(file= "GLFREC.csv", sep= ",", header=T, stringsAsFactors = F)
e5=read.csv(file ="INGEST_DATA.csv", sep= ",", header=T, stringsAsFactors = F )
e6=read.csv(file ="INVREC.csv", sep= ",", header=T, stringsAsFactors = F )
e7=read.csv(file ="ISTREC.csv", sep= ",", header=T, stringsAsFactors = F )
e8=read.csv(file ="NEWBIOCODESBIG.csv", sep= ",", header=T, stringsAsFactors = F )
e9=read.csv(file ="SHRREC.csv", sep= ",", header=T, stringsAsFactors = F )
e10=read.csv(file ="STAREC.csv", sep= ",", header=T, stringsAsFactors = F)
e11=read.csv(file ="STAREC_rev20190402.csv", sep= ",", header=T, stringsAsFactors = F )
e12=read.csv(file ="VESSELS.csv", sep= ",", header=T, stringsAsFactors = F )
e13 <- read.csv(file = "lg_camera_class_groupings_20170113_phylo_orderd.csv", header=T, sep=",", stringsAsFactors = F)
e14<- read.csv(file= "ENVREC.csv", sep= ",", header= T, stringsAsFactors = F)
+#TXTFILES
list.files()
d1<- read.table(file= "ISIIS201405281105.txt", sep=",", header=T, stringsAsFactors = F)
d2<- read.table(file= "ISIIS201405281124.txt", sep=",", header=T, stringsAsFactors=F)
d3<- read.table(file= "ISIIS201405281215.txt", sep=",", header=T, stringsAsFactors = F)
d4<- read.table(file= "ISIIS201405281609.txt", sep=",", header=T, stringsAsFactors = F)
d5<- read.table(file= "aurelia_15minCell_statareas.txt", sep=",", header=T, stringsAsFactors = F)
#EXCELFILES'
library(readxl)
a1= read_xlsx(path= "transect_towtime.xlsx", sheet=1, col_names=T)
a2= read_xlsx(path= "NameTranslator_table20140330.xlsx", sheet=1, col_names=T)
a3= read_xlsx(path= "Aurelia_SEAMAP_2012-2018_30minCell.xlsx", sheet=1, col_names=T)
#RDATA
load("aurelia_15minCell_statareas.Rdata")
